// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertEvents implements pgx.CopyFromSource.
type iteratorForInsertEvents struct {
	rows                 []InsertEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Type,
		r.rows[0].Source,
		r.rows[0].VisitorID,
		r.rows[0].SessionID,
		r.rows[0].Path,
		r.rows[0].Referrer,
		r.rows[0].UserAgent,
		r.rows[0].Country,
		r.rows[0].Props,
		r.rows[0].OccurredAt,
		r.rows[0].ReceivedAt,
	}, nil
}

func (r iteratorForInsertEvents) Err() error {
	return nil
}

func (q *Queries) InsertEvents(ctx context.Context, arg []InsertEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"events"}, []string{"type", "source", "visitor_id", "session_id", "path", "referrer", "user_agent", "country", "props", "occurred_at", "received_at"}, &iteratorForInsertEvents{rows: arg})
}
