// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type Event struct {
	ID         int64
	Type       string
	Source     string
	VisitorID  string
	SessionID  string
	Path       string
	Referrer   string
	UserAgent  string
	Country    string
	Props      json.RawMessage
	OccurredAt time.Time
	ReceivedAt time.Time
}

type Movie struct {
	ID            string
	Year          int32
	Day           int16
	Date          time.Time
	Title         string
	Directors     []string
	Description   string
	PosterPath    string
	ReleaseYear   *int32
	LetterboxdUrl string
	HostRating    *int16
}

type Rating struct {
	MovieID   string
	VisitorID string
	Value     int16
	CreatedAt time.Time
	UpdatedAt time.Time
}
