// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

type InsertEventsParams struct {
	Type       string
	Source     string
	VisitorID  string
	SessionID  string
	Path       string
	Referrer   string
	UserAgent  string
	Country    string
	Props      json.RawMessage
	OccurredAt time.Time
	ReceivedAt time.Time
}

const listMoviesByYear = `-- name: ListMoviesByYear :many
SELECT id, year, day, date, title, directors, description, poster_path, release_year, letterboxd_url, host_rating FROM movies WHERE year = $1 ORDER BY day
`

func (q *Queries) ListMoviesByYear(ctx context.Context, year int32) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMoviesByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Day,
			&i.Date,
			&i.Title,
			&i.Directors,
			&i.Description,
			&i.PosterPath,
			&i.ReleaseYear,
			&i.LetterboxdUrl,
			&i.HostRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movieExists = `-- name: MovieExists :one
SELECT EXISTS (SELECT 1 FROM movies WHERE id = $1)
`

func (q *Queries) MovieExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, movieExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ratingSummariesByYear = `-- name: RatingSummariesByYear :many
SELECT r.movie_id,
       avg(r.value)::float8                                                    AS average,
       count(*)                                                                AS count,
       COALESCE(max(r.value) FILTER (WHERE r.visitor_id = $1), 0)::smallint AS mine -- 0 = not rated
FROM ratings r
JOIN movies m ON m.id = r.movie_id
WHERE m.year = $2
GROUP BY r.movie_id
`

type RatingSummariesByYearParams struct {
	VisitorID string
	Year      int32
}

type RatingSummariesByYearRow struct {
	MovieID string
	Average float64
	Count   int64
	Mine    int16
}

func (q *Queries) RatingSummariesByYear(ctx context.Context, arg RatingSummariesByYearParams) ([]RatingSummariesByYearRow, error) {
	rows, err := q.db.Query(ctx, ratingSummariesByYear, arg.VisitorID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatingSummariesByYearRow
	for rows.Next() {
		var i RatingSummariesByYearRow
		if err := rows.Scan(
			&i.MovieID,
			&i.Average,
			&i.Count,
			&i.Mine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingSummary = `-- name: RatingSummary :one
SELECT COALESCE(avg(value), 0)::float8                              AS average,
       count(*)                                                     AS count,
       COALESCE(max(value) FILTER (WHERE visitor_id = $1), 0)::smallint AS mine -- 0 = not rated
FROM ratings
WHERE movie_id = $2
`

type RatingSummaryParams struct {
	VisitorID string
	MovieID   string
}

type RatingSummaryRow struct {
	Average float64
	Count   int64
	Mine    int16
}

func (q *Queries) RatingSummary(ctx context.Context, arg RatingSummaryParams) (RatingSummaryRow, error) {
	row := q.db.QueryRow(ctx, ratingSummary, arg.VisitorID, arg.MovieID)
	var i RatingSummaryRow
	err := row.Scan(&i.Average, &i.Count, &i.Mine)
	return i, err
}

const saveRating = `-- name: SaveRating :exec
INSERT INTO ratings (movie_id, visitor_id, value, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (movie_id, visitor_id)
DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at
`

type SaveRatingParams struct {
	MovieID   string
	VisitorID string
	Value     int16
	At        time.Time
}

func (q *Queries) SaveRating(ctx context.Context, arg SaveRatingParams) error {
	_, err := q.db.Exec(ctx, saveRating,
		arg.MovieID,
		arg.VisitorID,
		arg.Value,
		arg.At,
	)
	return err
}
