output "api_url" {
  value = google_cloud_run_v2_service.api.uri
}

output "site_url" {
  value = "https://${var.domain}"
}

output "images_url" {
  value = "https://${local.images_domain}"
}

output "turnstile_site_key" {
  value = cloudflare_turnstile_widget.comments.sitekey
}

# Non-secret identifiers that deploy scripts and GitHub Actions need. They're
# written to files in the repo (commit them) so local and CI deploys read the
# same values and nothing has to be copied by hand.

resource "local_file" "deploy_env" {
  filename        = "${path.module}/../deploy.env"
  file_permission = "0644"
  content         = <<-EOT
    # Generated by Terraform (infra/outputs.tf). Do not edit; run `make infra`.
    GCP_PROJECT=${var.gcp_project}
    GCP_REGION=${var.gcp_region}
    API_SERVICE=${google_cloud_run_v2_service.api.name}
    IMAGE_REPO=${local.image_repo}
    WIF_PROVIDER=${google_iam_workload_identity_pool_provider.github.name}
    DEPLOYER_SA=${google_service_account.deployer.email}
    CLOUDFLARE_ACCOUNT_ID=${var.cloudflare_account_id}
    PAGES_PROJECT=${cloudflare_pages_project.site.name}
    R2_BUCKET=${cloudflare_r2_bucket.images.name}
  EOT
}

resource "local_file" "web_env" {
  filename        = "${path.module}/../ts/apps/web/.env.production"
  file_permission = "0644"
  content         = <<-EOT
    # Generated by Terraform (infra/outputs.tf). Turnstile site keys are public.
    VITE_TURNSTILE_SITE_KEY=${cloudflare_turnstile_widget.comments.sitekey}
    VITE_LINEUP_YEAR=2025
  EOT
}
