// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Comment struct {
	ID         int64
	ThreadKey  string
	ParentID   *int64
	Depth      int16
	AuthorID   string
	AuthorName string
	Body       string
	Status     string
	CreatedAt  time.Time
}

type CommentReaction struct {
	CommentID int64
	AuthorID  string
	Emoji     string
	CreatedAt time.Time
}
