// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const addReaction = `-- name: AddReaction :exec
INSERT INTO comment_reactions (comment_id, author_id, emoji, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddReactionParams struct {
	CommentID int64
	AuthorID  string
	Emoji     string
	CreatedAt time.Time
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction,
		arg.CommentID,
		arg.AuthorID,
		arg.Emoji,
		arg.CreatedAt,
	)
	return err
}

const countCommentsByAuthorSince = `-- name: CountCommentsByAuthorSince :one
SELECT count(*) FROM comments WHERE author_id = $1 AND created_at >= $2
`

type CountCommentsByAuthorSinceParams struct {
	AuthorID  string
	CreatedAt time.Time
}

func (q *Queries) CountCommentsByAuthorSince(ctx context.Context, arg CountCommentsByAuthorSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByAuthorSince, arg.AuthorID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVisibleByThread = `-- name: CountVisibleByThread :many
SELECT thread_key, count(*) AS count
FROM comments
WHERE thread_key = ANY($1::text[]) AND status = 'visible'
GROUP BY thread_key
`

type CountVisibleByThreadRow struct {
	ThreadKey string
	Count     int64
}

func (q *Queries) CountVisibleByThread(ctx context.Context, threadKeys []string) ([]CountVisibleByThreadRow, error) {
	rows, err := q.db.Query(ctx, countVisibleByThread, threadKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountVisibleByThreadRow
	for rows.Next() {
		var i CountVisibleByThreadRow
		if err := rows.Scan(&i.ThreadKey, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComment = `-- name: GetComment :one
SELECT id, thread_key, parent_id, depth, author_id, author_name, body, status, created_at FROM comments WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ThreadKey,
		&i.ParentID,
		&i.Depth,
		&i.AuthorID,
		&i.AuthorName,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :one
INSERT INTO comments (thread_key, parent_id, depth, author_id, author_name, body, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, thread_key, parent_id, depth, author_id, author_name, body, status, created_at
`

type InsertCommentParams struct {
	ThreadKey  string
	ParentID   *int64
	Depth      int16
	AuthorID   string
	AuthorName string
	Body       string
	Status     string
	CreatedAt  time.Time
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, insertComment,
		arg.ThreadKey,
		arg.ParentID,
		arg.Depth,
		arg.AuthorID,
		arg.AuthorName,
		arg.Body,
		arg.Status,
		arg.CreatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ThreadKey,
		&i.ParentID,
		&i.Depth,
		&i.AuthorID,
		&i.AuthorName,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listReactions = `-- name: ListReactions :many
SELECT comment_id, author_id, emoji, created_at FROM comment_reactions
WHERE comment_id = ANY($1::bigint[])
ORDER BY created_at, comment_id, emoji, author_id
`

func (q *Queries) ListReactions(ctx context.Context, ids []int64) ([]CommentReaction, error) {
	rows, err := q.db.Query(ctx, listReactions, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentReaction
	for rows.Next() {
		var i CommentReaction
		if err := rows.Scan(
			&i.CommentID,
			&i.AuthorID,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThread = `-- name: ListThread :many
WITH RECURSIVE thread AS (
    (SELECT r.id, r.thread_key, r.parent_id, r.depth, r.author_id, r.author_name, r.body, r.status, r.created_at FROM comments r
     WHERE r.thread_key = $1
       AND r.parent_id IS NULL
       AND ($2::bigint = 0 OR r.id < $2::bigint)
     ORDER BY r.id DESC
     LIMIT $3)
    UNION ALL
    SELECT c.id, c.thread_key, c.parent_id, c.depth, c.author_id, c.author_name, c.body, c.status, c.created_at FROM comments c JOIN thread t ON c.parent_id = t.id
)
SELECT id, thread_key, parent_id, depth, author_id, author_name, body, status, created_at FROM thread
`

type ListThreadParams struct {
	ThreadKey string
	BeforeID  int64
	PageSize  int32
}

type ListThreadRow struct {
	ID         int64
	ThreadKey  string
	ParentID   *int64
	Depth      int16
	AuthorID   string
	AuthorName string
	Body       string
	Status     string
	CreatedAt  time.Time
}

// ListThread fetches one page of top-level comments (newest first, older than
// before_id unless it is 0) plus every reply beneath them, in one query.
func (q *Queries) ListThread(ctx context.Context, arg ListThreadParams) ([]ListThreadRow, error) {
	rows, err := q.db.Query(ctx, listThread, arg.ThreadKey, arg.BeforeID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadRow
	for rows.Next() {
		var i ListThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadKey,
			&i.ParentID,
			&i.Depth,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM comment_reactions WHERE comment_id = $1 AND author_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	CommentID int64
	AuthorID  string
	Emoji     string
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.CommentID, arg.AuthorID, arg.Emoji)
	return err
}

const setCommentStatus = `-- name: SetCommentStatus :execrows
UPDATE comments SET status = $2 WHERE id = $1
`

type SetCommentStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) SetCommentStatus(ctx context.Context, arg SetCommentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCommentStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
