-- The 2025 lineup, migrated from the old hard-coded src/data/movies.js.
-- Fixes from TASKS.md: Weapons (2025) is directed by Zach Cregger, and its
-- description now matches that film.
INSERT INTO movies (id, year, day, date, title, directors, description, poster_path, host_rating)
VALUES
    ('2025-01', 2025, 1, '2025-10-01', 'Christine',
     ARRAY['John Carpenter'],
     'Nerdy high schooler Arnie Cunningham falls for Christine, a rusty 1958 Plymouth Fury, and becomes obsessed with restoring the classic automobile to her former glory. As the car changes, so does Arnie, whose newfound confidence turns to arrogance behind the wheel of his exotic beauty. Arnie’s girlfriend Leigh and best friend Dennis reach out to him, only to be met by a Fury like no other.',
     'posters/christine.jpg', 7),
    ('2025-02', 2025, 2, '2025-10-02', 'The Grudge',
     ARRAY['Takashi Shimizu'],
     'An American nurse living and working in Tokyo is exposed to a mysterious supernatural curse, one that locks a person in a powerful rage before claiming their life and spreading to another victim.',
     'posters/thegrudge.jpg', 8),
    ('2025-03', 2025, 3, '2025-10-03', 'Eraserhead',
     ARRAY['David Lynch'],
     'First-time father Henry Spencer tries to survive his industrial environment, his angry girlfriend, and the unbearable screams of his newly born mutant child.',
     'posters/eraserhead.jpg', 9),
    ('2025-04', 2025, 4, '2025-10-04', 'The Babadook',
     ARRAY['Jennifer Kent'],
     'A single mother, plagued by the violent death of her husband, battles with her son''s fear of a monster lurking in the house, but soon discovers a sinister presence all around her.',
     'posters/thebabadook.jpg', 8),
    ('2025-05', 2025, 5, '2025-10-05', 'Shutter',
     ARRAY['Banjong Pisanthanakun', 'Parkpoom Wongpoom'],
     'A young photographer and his girlfriend discover mysterious shadows in their photographs after a tragic accident. As they investigate the phenomenon, they uncover a haunting secret that threatens to consume them both.',
     'posters/shutter.jpg', 7),
    ('2025-06', 2025, 6, '2025-10-06', 'Silent Hill',
     ARRAY['Christophe Gans'],
     'A mother goes in search for her adopted daughter in a strange, desolate town called Silent Hill. She soon discovers that the town is not as deserted as it seems, and that dark forces are at work.',
     'posters/silenthill.jpg', 6),
    ('2025-07', 2025, 7, '2025-10-07', 'Practical Magic',
     ARRAY['Griffin Dunne'],
     'Two sisters, raised by their aunts in a small town, struggle to break a family curse that dooms all their relationships. As they navigate love and loss, they must also confront the dark forces that threaten to tear them apart.',
     'posters/practicalmagic.jpg', 7),
    ('2025-08', 2025, 8, '2025-10-08', 'The Thing',
     ARRAY['John Carpenter'],
     'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims. As paranoia and mistrust grow among the team members, they must find a way to survive the deadly creature before it destroys them all.',
     'posters/thething.jpg', 9),
    ('2025-09', 2025, 9, '2025-10-09', 'The Omen',
     ARRAY['Richard Donner'],
     'A diplomat and his wife adopt a child, only to discover that he is the Antichrist. As strange and deadly events begin to occur around them, they must find a way to stop them before it''s too late.',
     'posters/theomen.jpg', 8),
    ('2025-10', 2025, 10, '2025-10-10', 'Mirrors',
     ARRAY['Alexandre Aja'],
     'A former detective takes a job as a night watchman at a department store that has been ravaged by fire. He soon discovers that the mirrors in the store are portals to a dark and malevolent world, and that they are slowly driving him insane.',
     'posters/mirrors.jpg', 5),
    ('2025-11', 2025, 11, '2025-10-11', 'Weapons',
     ARRAY['Zach Cregger'],
     'When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.',
     'posters/weapons.jpg', 6),
    ('2025-12', 2025, 12, '2025-10-12', 'A Nightmare on Elm Street',
     ARRAY['Wes Craven'],
     'A group of teenagers in a small town are terrorized in their dreams by the vengeful spirit of a disfigured serial killer, Freddy Krueger. As the line between dreams and reality blurs, they must find a way to confront their fears and stop Freddy before he claims more victims.',
     'posters/anightmareonelmstreet.jpg', 8),
    ('2025-13', 2025, 13, '2025-10-13', 'Friday the 13th: The Final Chapter',
     ARRAY['Joseph Zito'],
     'After a series of brutal murders at Camp Crystal Lake, a group of teenagers must band together to survive the night and confront the relentless killer, Jason Voorhees. As they fight for their lives, they uncover dark secrets about the camp''s past that may hold the key to stopping the madness.',
     'posters/fridaythe13th4.jpg', 7),
    ('2025-14', 2025, 14, '2025-10-14', 'Incantation',
     ARRAY['Kevin Ko'],
     'A young woman must confront her past and the dark forces that haunt her family when she returns to her ancestral home to care for her ailing grandmother. As she delves deeper into the family''s history, she uncovers a terrifying secret that threatens to consume her.',
     'posters/incantation.jpg', 7),
    ('2025-15', 2025, 15, '2025-10-15', 'As Above, So Below',
     ARRAY['John Erick Dowdle'],
     'A team of explorers ventures into the catacombs beneath Paris in search of a lost treasure, only to discover that the underground labyrinth holds dark secrets and terrifying dangers that threaten their sanity and survival.',
     'posters/asabovesobelow.jpg', 6),
    ('2025-16', 2025, 16, '2025-10-16', '30 Days of Night',
     ARRAY['David Slade'],
     'In a small Alaskan town, a group of vampires descends upon the community during its annual month-long polar night, when the sun doesn''t rise. The townspeople must band together to survive the relentless onslaught of the bloodthirsty creatures.',
     'posters/30daysofnight.jpg', 7),
    ('2025-17', 2025, 17, '2025-10-17', 'Lights Out',
     ARRAY['David F. Sandberg'],
     'A family is haunted by a malevolent entity that only appears in the dark. As they struggle to uncover the truth behind the haunting, they must confront their own fears and secrets in order to survive.',
     'posters/lightsout.jpg', 6),
    ('2025-18', 2025, 18, '2025-10-18', 'Terrifier 3',
     ARRAY['Damien Leone'],
     'The third installment in the Terrifier series, following the sadistic clown Art as he continues his reign of terror. This time, Art faces new challenges and adversaries, leading to even more gruesome and horrifying encounters.',
     'posters/terrifier3.jpg', 7),
    ('2025-19', 2025, 19, '2025-10-19', 'The Craft',
     ARRAY['Andrew Fleming'],
     'A group of four high school girls discover their powers as witches and use them to exact revenge on those who have wronged them. However, their newfound abilities come with dangerous consequences that threaten to spiral out of control.',
     'posters/thecraft.jpg', 7),
    ('2025-20', 2025, 20, '2025-10-20', 'Battle Royale',
     ARRAY['Kinji Fukasaku'],
     'In a dystopian future, a class of high school students is forced to participate in a deadly game where they must fight to the death until only one remains. As alliances are formed and betrayals occur, the students must navigate the brutal competition while questioning their own morality.',
     'posters/battleroyale.jpg', 8),
    ('2025-21', 2025, 21, '2025-10-21', 'The Ring',
     ARRAY['Gore Verbinski'],
     'A journalist investigates a mysterious videotape that is said to cause the death of anyone who watches it within seven days. As she delves deeper into the tape''s origins, she uncovers a dark and terrifying secret that puts her own life in danger.',
     'posters/thering.jpg', 8),
    ('2025-22', 2025, 22, '2025-10-22', 'Texas Chainsaw Massacre',
     ARRAY['Tobe Hooper'],
     'A group of friends on a road trip in rural Texas encounter a family of cannibals, including the infamous Leatherface, who wields a chainsaw. As they fight for their lives, they must confront the horrors of the isolated and twisted world they have stumbled into.',
     'posters/tcm.jpg', 9),
    ('2025-23', 2025, 23, '2025-10-23', 'What Lies Beneath',
     ARRAY['Robert Zemeckis'],
     'A married couple''s seemingly perfect life is shattered when the wife begins to experience terrifying supernatural occurrences in their home. As she delves deeper into the mystery, she uncovers dark secrets that threaten to destroy their relationship and her sanity.',
     'posters/whatliesbeneath.jpg', 7),
    ('2025-24', 2025, 24, '2025-10-24', 'Thanksgiving',
     ARRAY['Eli Roth'],
     'A group of friends gathers for a Thanksgiving dinner, only to find themselves trapped in a deadly game of survival when a masked killer begins to pick them off one by one. As they fight for their lives, they must also confront their own secrets and betrayals.',
     'posters/thanksgiving.jpg', 6),
    ('2025-25', 2025, 25, '2025-10-25', 'The Village',
     ARRAY['M. Night Shyamalan'],
     'In a secluded village surrounded by woods, the residents live in fear of mysterious creatures that inhabit the forest. When a young man from the village ventures into the woods to seek medical help for his injured love, he uncovers shocking truths about their way of life.',
     'posters/thevillage.jpg', 7),
    ('2025-26', 2025, 26, '2025-10-26', 'The Hills Have Eyes',
     ARRAY['Wes Craven'],
     'A family on a road trip becomes stranded in a desert and is hunted by a group of cannibalistic mutants. As they fight for survival, they must confront their own fears and the horrors of the wasteland.',
     'posters/thehillshaveeyes.jpg', 6),
    ('2025-27', 2025, 27, '2025-10-27', 'The Others',
     ARRAY['Alejandro Amenábar'],
     'A woman and her two photosensitive children live in a darkened mansion, where they begin to experience strange and terrifying occurrences. As they try to uncover the truth behind the haunting, they must confront their own fears and the secrets of the past.',
     'posters/theothers.jpg', 8),
    ('2025-28', 2025, 28, '2025-10-28', 'House of Psychotic Women',
     ARRAY['Jackie Strano'],
     'A documentary exploring the life and work of filmmaker and actress Mary Harron, known for her portrayal of complex and troubled women in cult horror films. The film delves into Harron''s personal struggles and the themes of mental illness and identity in her work.',
     'posters/hopw.jpg', 6),
    ('2025-29', 2025, 29, '2025-10-29', 'Gonjiam: Haunted Asylum',
     ARRAY['Hwang Dong-hyuk'],
     'A group of people exploring an abandoned asylum for a horror web series encounter terrifying supernatural phenomena. As they delve deeper into the asylum''s dark history, they must confront their own fears and the malevolent forces that haunt the building.',
     'posters/gonjiam.jpg', 7),
    ('2025-30', 2025, 30, '2025-10-30', 'Afflicted',
     ARRAY['Derek Lee', 'Clif Prowse'],
     'Two friends set out on a year-long trip around the world, documenting their experiences. However, one of them becomes infected with a mysterious illness that gives him supernatural abilities, leading to a terrifying transformation and a struggle for survival.',
     'posters/afflicted.jpg', 7),
    ('2025-31', 2025, 31, '2025-10-31', 'Night of the Living Dead',
     ARRAY['George A. Romero'],
     'A group of people trapped in a farmhouse must defend themselves against a horde of flesh-eating zombies. As they struggle to survive, they must also confront their own fears and the breakdown of society in the face of the undead apocalypse.',
     'posters/nightofthelivingdead.jpg', 7);
