-- The 2026 lineup, imported from the Letterboxd list (in list order).
-- Descriptions are the Letterboxd synopses; host_rating is the list owner's
-- Letterboxd rating (0.5–5 stars = 1–10), NULL where there isn't one yet.
INSERT INTO lineups (year, letterboxd_list_url)
VALUES (2026, 'https://letterboxd.com/mattmo/list/31-nights-of-horror-2026/');

INSERT INTO movies (id, year, day, date, title, directors, description, poster_path, release_year, letterboxd_url, host_rating)
VALUES
    ('2026-01', 2026, 1, '2026-10-01', 'Backrooms',
     ARRAY['Kane Parsons'],
     'A strange doorway appears in the basement of a furniture showroom.',
     'posters/backrooms-2026.jpg', 2026, 'https://letterboxd.com/film/backrooms-2026/', NULL),
    ('2026-02', 2026, 2, '2026-10-02', 'Absentia',
     ARRAY['Mike Flanagan'],
     'Tricia''s husband has been missing for seven years. Her younger sister Callie comes to live with her as the pressure mounts to finally declare him ''dead in absentia''. Tricia is reluctant, always holding out hope, but Callie is practical and wants her to move on. As Tricia sifts through the wreckage and tries to move on with her life, Callie finds herself drawn to an ominous tunnel near the house.',
     'posters/absentia.jpg', 2011, 'https://letterboxd.com/film/absentia/', NULL),
    ('2026-03', 2026, 3, '2026-10-03', 'A Nightmare on Elm Street 3: Dream Warriors',
     ARRAY['Chuck Russell'],
     'A psychiatrist, familiar with the knife-wielding dream demon Freddy Krueger, helps teens at a mental hospital battle the killer who is invading their dreams.',
     'posters/a-nightmare-on-elm-street-3-dream-warriors.jpg', 1987, 'https://letterboxd.com/film/a-nightmare-on-elm-street-3-dream-warriors/', NULL),
    ('2026-04', 2026, 4, '2026-10-04', 'Exit 8',
     ARRAY['Genki Kawamura'],
     'A man trapped in an endless sterile subway passageway sets out to find Exit 8. The rules of his quest are simple: do not overlook anything out of the ordinary. If you discover an anomaly, turn back immediately. If you don’t, carry on. Then leave from Exit 8. But even a single oversight will send him back to the beginning. Will he ever reach his goal and escape this infinite corridor?',
     'posters/exit-8.jpg', 2025, 'https://letterboxd.com/film/exit-8/', NULL),
    ('2026-05', 2026, 5, '2026-10-05', 'Late Night with the Devil',
     ARRAY['Cameron Cairnes', 'Colin Cairnes'],
     'A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation''s living rooms.',
     'posters/late-night-with-the-devil.jpg', 2023, 'https://letterboxd.com/film/late-night-with-the-devil/', 7),
    ('2026-06', 2026, 6, '2026-10-06', 'Vertigo',
     ARRAY['Alfred Hitchcock'],
     'A retired San Francisco detective suffering from acrophobia investigates the strange activities of an old friend''s wife, all the while becoming dangerously obsessed with her.',
     'posters/vertigo.jpg', 1958, 'https://letterboxd.com/film/vertigo/', NULL),
    ('2026-07', 2026, 7, '2026-10-07', 'Trick ''r Treat',
     ARRAY['Michael Dougherty'],
     'Four interwoven stories that occur on Halloween: an everyday high school principal has a secret life as a serial killer; a college virgin might have just met the one guy for her; a group of teenagers pull a mean prank, and a bitter old recluse receives an uninvited guest.',
     'posters/trick-r-treat.jpg', 2007, 'https://letterboxd.com/film/trick-r-treat/', NULL),
    ('2026-08', 2026, 8, '2026-10-08', 'Hostel: Part II',
     ARRAY['Eli Roth'],
     'Three American college students studying abroad are lured to a Slovakian hostel, and discover the grim reality behind it.',
     'posters/hostel-part-ii.jpg', 2007, 'https://letterboxd.com/film/hostel-part-ii/', NULL),
    ('2026-09', 2026, 9, '2026-10-09', 'Ouija: Origin of Evil',
     ARRAY['Mike Flanagan'],
     'In 1967 Los Angeles, a widowed mother and her two daughters add a new stunt to bolster their séance scam business and unwittingly invite authentic evil into their home. When the youngest daughter is overtaken by the merciless spirit, this small family confronts unthinkable fears to save her and send her possessor back to the other side.',
     'posters/ouija-origin-of-evil.jpg', 2016, 'https://letterboxd.com/film/ouija-origin-of-evil/', NULL),
    ('2026-10', 2026, 10, '2026-10-10', 'KINKI',
     ARRAY['Koji Shiraishi'],
     'After an editor of an occult magazine suddenly vanishes, his friend Chihiro and his co-worker Yusei set out to discover the reason behind his disappearance.',
     'posters/kinki-2025.jpg', 2025, 'https://letterboxd.com/film/kinki-2025/', NULL),
    ('2026-11', 2026, 11, '2026-10-11', 'The Devil''s Rejects',
     ARRAY['Rob Zombie'],
     'The murderous, backwoods Firefly family take to the road to escape the vengeful Sheriff Wydell, who is not afraid of being as ruthless as his target.',
     'posters/the-devils-rejects.jpg', 2005, 'https://letterboxd.com/film/the-devils-rejects/', NULL),
    ('2026-12', 2026, 12, '2026-10-12', 'Drag Me to Hell',
     ARRAY['Sam Raimi'],
     'After denying a woman the extension she needs to keep her home, loan officer Christine Brown sees her once-promising life take a startling turn for the worse. Christine is convinced she''s been cursed by a Gypsy, but her boyfriend is skeptical. Her only hope seems to lie in a psychic who claims he can help her lift the curse and keep her soul from being dragged straight to hell.',
     'posters/drag-me-to-hell.jpg', 2009, 'https://letterboxd.com/film/drag-me-to-hell/', NULL),
    ('2026-13', 2026, 13, '2026-10-13', 'Teenage Sex and Death at Camp Miasma',
     ARRAY['Jane Schoenbrun'],
     'After years of slapdash sequels and waning fandom, the Camp Miasma slasher franchise is handed over to an enthusiastic young director for resurrection. But when she visits the original''s star, a now-reclusive actress shrouded in mystery, the two women fall into a blood-soaked world of desire, fear, and delirium.',
     'posters/teenage-sex-and-death-at-camp-miasma.jpg', 2026, 'https://letterboxd.com/film/teenage-sex-and-death-at-camp-miasma/', NULL),
    ('2026-14', 2026, 14, '2026-10-14', 'Malignant',
     ARRAY['James Wan'],
     'Madison is paralyzed by shocking visions of grisly murders, and her torment worsens as she discovers that these waking dreams are in fact terrifying realities with a mysterious tie to her past.',
     'posters/malignant-2021.jpg', 2021, 'https://letterboxd.com/film/malignant-2021/', NULL),
    ('2026-15', 2026, 15, '2026-10-15', 'Revenge',
     ARRAY['Coralie Fargeat'],
     'Jen''s romantic getaway with her wealthy married boyfriend is disrupted when his friends arrive for an impromptu hunting trip. Tension mounts at the house until the situation culminates in an unexpected way.',
     'posters/revenge-2017.jpg', 2017, 'https://letterboxd.com/film/revenge-2017/', NULL),
    ('2026-16', 2026, 16, '2026-10-16', 'They Will Kill You',
     ARRAY['Kirill Sokolov'],
     'A woman answers a help wanted ad to be a housekeeper in a mysterious New York City high-rise, unaware that she is entering a community that has seen a number of disappearances over the years and may be under the grip of a Satanic cult.',
     'posters/they-will-kill-you.jpg', 2026, 'https://letterboxd.com/film/they-will-kill-you/', NULL),
    ('2026-17', 2026, 17, '2026-10-17', 'Satanic Hispanics',
     ARRAY['Mike Mendez', 'Demián Rugna', 'Eduardo Sánchez', 'Gigi Saul Guerrero', 'Alejandro Brugués'],
     'When police raid a house in El Paso, they find it full of dead Latinos, and only one survivor. He’s known as The Traveler, and when they take him to the station for questioning, he tells them those lands are full of magic and talks about the horrors he’s encountered in his long time on this earth, about portals to other worlds, mythical creatures, demons and the undead. Stories about Latin American legends.',
     'posters/satanic-hispanics.jpg', 2022, 'https://letterboxd.com/film/satanic-hispanics/', NULL),
    ('2026-18', 2026, 18, '2026-10-18', 'Passenger',
     ARRAY['André Øvredal'],
     'After a young couple witnesses a gruesome highway accident, they soon realize they did not leave the crash scene alone, as a demonic presence called the Passenger that won''t stop until it claims them both turns their van life adventure into a nightmare.',
     'posters/passenger-2026.jpg', 2026, 'https://letterboxd.com/film/passenger-2026/', NULL),
    ('2026-19', 2026, 19, '2026-10-19', 'Kwaidan',
     ARRAY['Masaki Kobayashi'],
     'Taking its title from an archaic Japanese word meaning "ghost story," this anthology adapts four folk tales. A penniless samurai marries for money with tragic results. A man stranded in a blizzard is saved by Yuki the Snow Maiden, but his rescue comes at a cost. Blind musician Hoichi is forced to perform for an audience of ghosts. An author relates the story of a samurai who sees another warrior''s reflection in his teacup.',
     'posters/kwaidan.jpg', 1964, 'https://letterboxd.com/film/kwaidan/', NULL),
    ('2026-20', 2026, 20, '2026-10-20', 'Possum',
     ARRAY['Matthew Holness'],
     'A disgraced children''s puppeteer returns to his childhood home and is forced to confront his wicked stepfather and the secrets that have tortured him his entire life.',
     'posters/possum.jpg', 2018, 'https://letterboxd.com/film/possum/', NULL),
    ('2026-21', 2026, 21, '2026-10-21', 'Noroi: The Curse',
     ARRAY['Koji Shiraishi'],
     'A documentary filmmaker explores seemingly unrelated paranormal incidents connected by the legend of an ancient demon.',
     'posters/noroi-the-curse.jpg', 2005, 'https://letterboxd.com/film/noroi-the-curse/', 8),
    ('2026-22', 2026, 22, '2026-10-22', 'The Descent',
     ARRAY['Neil Marshall'],
     'After a personal tragedy, Sarah joins her friends on a caving expedition in the Appalachian Mountains. But when a rockfall traps them deep underground, their adventure turns into a nightmare. As they search for a way out, the group discovers they are not alone—lurking in the darkness are savage, cave-dwelling creatures. With rising tension and dwindling trust, the women must fight to survive against both the predators and each other.',
     'posters/the-descent.jpg', 2005, 'https://letterboxd.com/film/the-descent/', NULL),
    ('2026-23', 2026, 23, '2026-10-23', 'Possession',
     ARRAY['Andrzej Żuławski'],
     'A young woman left her family for an unspecified reason. The husband determines to find out the truth and starts following his wife. At first, he suspects that a man is involved. But gradually, he finds out more and more strange behaviors and bizarre incidents that indicate something more than a possessed love affair.',
     'posters/possession.jpg', 1981, 'https://letterboxd.com/film/possession/', NULL),
    ('2026-24', 2026, 24, '2026-10-24', 'MadS',
     ARRAY['David Moreau'],
     'A teenager stops off to see his dealer to test a new drug before heading off for a night of partying. On the way home, he picks up an injured woman, and the night takes a surreal turn.',
     'posters/mads.jpg', 2024, 'https://letterboxd.com/film/mads/', NULL),
    ('2026-25', 2026, 25, '2026-10-25', 'Hell House LLC',
     ARRAY['Stephen Cognetti'],
     'Five years after an unexplained malfunction causes the death of 15 tour-goers and staff on the opening night of a Halloween haunted house tour, a documentary crew travels back to the scene of the tragedy to find out what really happened.',
     'posters/hell-house-llc.jpg', 2015, 'https://letterboxd.com/film/hell-house-llc/', NULL),
    ('2026-26', 2026, 26, '2026-10-26', 'When Evil Lurks',
     ARRAY['Demián Rugna'],
     'When brothers Pedro and Jimi discover that a demonic infection has been festering in a nearby farmhouse, they attempt to evict the victim from their land. Failing to adhere to the proper rites of exorcism, their reckless actions inadvertently trigger an epidemic of possessions across their rural community.',
     'posters/when-evil-lurks.jpg', 2023, 'https://letterboxd.com/film/when-evil-lurks/', NULL);
