name: Build and Deploy (CRA → GitHub Pages)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # 👇 point cache at the lockfile in the subfolder
          cache-dependency-path: spooky-movie-calendar/package-lock.json

      - name: Install
        run: npm ci
        working-directory: spooky-movie-calendar

      - name: Build (CRA)
        run: npm run build
        working-directory: spooky-movie-calendar
        env:
          # CRA picks PUBLIC_URL from "homepage" in package.json,
          # but this line is harmless and can help if homepage is missing.
          PUBLIC_URL: /spooky-movie-calendar

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: spooky-movie-calendar/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

